/*
 * CHANGE LOG - keep only last 5 threads
 * 
 * docs.microsoft
 * https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-hardwareinput
 */
using System.Runtime.InteropServices;

namespace UiaWebDriverServer.Contracts
{
    /// <summary>
    /// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct HardwareInput
    {
        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public uint uMsg;

        /// <summary>
        /// The low-order word of the lParam parameter for uMsg.
        /// </summary>
        public ushort wParamL;

        /// <summary>
        /// The high-order word of the lParam parameter for uMsg.
        /// </summary>
        public ushort wParamH;
    }
}
